version: "3.9"
services:
  dweebui:
    container_name: dweebui
    image: lllllllillllllillll/dweebui:v0.09-dev
    # build:
    #   context: .
    environment:
      NODE_ENV: production
      PORT: 8000
      SECRET: MrWiskers
      #Proxy_Manager: enabled
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - dweebui:/app
      - caddyfiles:/app/caddyfiles
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./custom-templates.json:/app/custom-templates.json
      #- ./composefiles:/app/composefiles
    networks:
      - dweeb_network

volumes:
  dweebui:
  caddyfiles:

networks:
  dweeb_network:
    driver: bridge
