version: "3.9"
services:
  dweebui:
    container_name: dweebui
    # image: lllllllillllllillll/dweebui:v0.20
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: 8000
      SECRET: MrWiskers
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - dweebui:/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dweebui_net

volumes:
  dweebui:

networks:
  dweebui_net:
    driver: bridge
